name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Escolha o módulo para destruir o Terraform"
        required: true
        type: choice
        options:
          - cognito
          - eks
          - rds
          - network

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Login
        env:
          HASHICORP_TOKEN: ${{ secrets.HASHICORP_TOKEN }}
        run: |
          mkdir -p ~/.terraform.d
          echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"$HASHICORP_TOKEN\"}}}" > ~/.terraform.d/credentials.tfrc.json
          echo "Autenticado no Terraform Cloud."

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init and Destroy
        working-directory: terraform/${{ github.event.inputs.module }}
        run: |
          terraform init
          terraform destroy -auto-approve

