name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Escolha o módulo para aplicar o Terraform"
        required: true
        type: choice
        options:
          - cognito
          - eks
          - network

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Login
        env:
          HASHICORP_TOKEN: ${{ secrets.HASHICORP_TOKEN }}
        run: |
          mkdir -p ~/.terraform.d
          echo "{\"credentials\":{\"app.terraform.io\":{\"token\":\"$HASHICORP_TOKEN\"}}}" > ~/.terraform.d/credentials.tfrc.json
          echo "Autenticado no Terraform Cloud."

      - name: Export Terraform Variables
        run: |
          echo "TF_VAR_AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init and Destroy
        working-directory: terraform/${{ github.event.inputs.module }}
        run: |
          terraform init
          terraform destroy -auto-approve
