name: Kubernetes Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.3'

      - name: Configure Kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name techchalenge-eks-cluster \
            --region us-east-1

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f kubernetes/

      - name: Check Pods Status
        run: |
          kubectl get pods -o wide
